### ISSUE TITLE
Error 500 Not Found.

### ISSUE THREAD

**Issue by harsimrat99** [CloudClub-uoft/cloud-club-website#43]
https://github.com/CloudClub-uoft/cloud-club-website/blob/c9625a2ff54df56c1e2a0bc6006f5214293052e4/routes/GET-forum.js#L4

The forum page resorts to an error 500 not found sometimes after the server has been up for a while. It might be an issue with the database connection timing out between Node and MySQL.

**Comment by JLefebvre55** [comment]
Fixed in recent commits.
