### ISSUE TITLE
Test Failure: test_forum.py

### ISSUE THREAD

**Issue by harsimrat99** [CloudClub-uoft/cloud-club-website#85]
Test failure detected for test_forum.py. An key error is being detected for the month 'Jun'

## Expected Behavior

All tests should pass successfully.

## Current Behavior

ERROR: test_sort_by_oldest_post_first

ERROR: test_sort_by_newest_post_first 

## Steps to Reproduce

1. Change directory to test/frontend/forum
2. Run test_forum.py script.
3. Observe failures in the command line.

## Context (Environment)

This issue was observed on the staging branch.
Selenium uses a chromium webdriver (Google Chrome).

Tests should pass to ensure that users are interacting with a robust system. Any test failures should be dealt with prudence and their root cause should be determined.

## Detailed Description

PASTING ERROR LOG:

Traceback (most recent call last):
  File "\cloud-club-website\test\frontend\forum\test_forum.py", line 133, in test_sort_by_newest_post_first
    all_poster_dates_text = [
  File "\cloud-club-website\test\frontend\forum\test_forum.py", line 134, in <listcomp>
    convert_post_date_to_yyyymmdd(strip_name(name.text))
  File "../testlib\forum.py", line 67, in **convert_post_date_to_yyyymmdd**
    **month_to_number[date_to_list[0]],**
    
**KeyError: 'Jun**

**Comment by qingyuan-wu** [comment]
PR: https://github.com/CloudClub-uoft/cloud-club-website/pull/89
